### ISSUE TITLE
The "-s" option does not exist.

### ISSUE THREAD

**Issue by matovu-ronald** [tiagomichaelsousa/LaravelResources#15]
When running the command "php artisan resources:create Article"
On this level below, when I press enter it throws the error, The "-s" option does not exist.
 Should I create the seeder for Article? (yes/no) [yes]:
 > 

I don't know whether that is the intended behaviour or not but probably it seems like an error to me.
But thanks for this great package probably I am going to make a simple article and a youtube video on how to use this package it really comes in handy.

**Comment by tiagomichaelsousa** [comment]
Hi @matovu-ronald, thank you for the feedback.

Did you tried to pass the flag -s when running the artisan command like this `php artisan resources:create Article -s` ? The package only comes with the default flags from artisan commands.

<img width="866" alt="Screenshot 2020-02-15 at 11 13 39" src="https://user-images.githubusercontent.com/28356381/74586958-02b8ec00-4fe5-11ea-96c5-dadf5cfd34b7.png">

Can you tell me which version of laravel and php are you using? I tried to reproduce your error but i couldn't.

Besides that, thank you for the support! If you make the video to explain how to use it please send me the url, i will check it out and add you to the contributors as tutorial ✅, docs 📖 and content 🖋

**Comment by matovu-ronald** [comment]
I tried it out and it throws this error.

The "-s" option does not exist.

**Comment by matovu-ronald** [comment]
Below is my laravel version in the require object
"require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0"
    }
php version  7.4.1

You can have a look at the screen recording of the error.
https://www.youtube.com/watch?v=5NSH7gT0S-A

**Comment by tiagomichaelsousa** [comment]
> Below is my laravel version in the require object
> "require": {
> "php": "^7.2",
> "fideloper/proxy": "^4.0",
> "laravel/framework": "^6.2",
> "laravel/tinker": "^2.0"
> }
> php version 7.4.1
> 
> You can have a look at the screen recording of the error.
> [https://youtu.be/5NSH7gT0S-A](url)

I'm using the same version of laravel but with the php 7.4.2 version and i couldn't reproduce the error. Can you update the screen recording of the error? I think it was not upload successfully.

Thank you! 🚀

**Comment by matovu-ronald** [comment]
Here is the video url
https://www.youtube.com/watch?v=5NSH7gT0S-A

**Comment by tiagomichaelsousa** [comment]
> Here is the video url
> https://www.youtube.com/watch?v=5NSH7gT0S-A

The -s flag is related to the seeder when you create the resources for a modal that doesn't exists. 

Can you please run `php artisan make:model --help` to check which flags that are available to you ? Please upload an image from your output or tell me if the -s or --seed is present.

Thank you! 🚀

**Comment by matovu-ronald** [comment]
<img width="1280" alt="Screen Shot 2020-02-16 at 5 50 19 PM" src="https://user-images.githubusercontent.com/20243540/74606850-e8663780-50e4-11ea-89c3-6bfe27f50628.png">
Here is the preview of my image after running `php artisan make:model --help`

**Comment by matovu-ronald** [comment]
<img width="1280" alt="Screen Shot 2020-02-16 at 7 23 55 PM" src="https://user-images.githubusercontent.com/20243540/74608435-fff7ed00-50f1-11ea-90a5-5bada2341646.png">
I did create a new laravel project and I guess --seed option that didn't exist in the previous project does exist and thus everything works properly, I believe it is was a result of my project lacking the --seed option for the `php artisan make:model `artisan command. Why --seed option doesn't exit I really cannot tell.
But everything now works just fine, and I think this issue should be closed since it cannot be reproduced in other projects.

**Comment by Mandoz13** [comment]
usually this happens when you forget to put one extra - so, always put -- before your command line.
