### ISSUE TITLE
Config models.namespace doesn't work

### ISSUE THREAD

**Issue by psaulus** [tiagomichaelsousa/LaravelResources#19]
When I changed value of `laravel-resources.models.namespace` then I expects that when I will write `php artisan resources:create Test` this will create model _Test_ in right namespace. But this doesn't work.

*Example*
I had changed the configuration on _App\Models_ after that I ran `php artisan resources:create Test`.

After that the model still is generated in /app directory but with namespace _App\Models_

**Comment by tiagomichaelsousa** [comment]
Hi @policeman16 

Yes, you are right, because when the model doesn't exist it will run `php artisan make:model`. I will try to fix it by the end of the day! 

Thank you for your feedback 🚀

**Comment by psaulus** [comment]
I will be grateful :)

**Comment by tiagomichaelsousa** [comment]
Hey @policeman16, the issue must be solved with the new version.
Upgrade your dependency to `"tiagomichaelsousa/laravelresources": "^1.5"` on composer.json file and you will be able to create the models in the namespace 🚀

Waiting for your feedback!

Thank you,
Tiago Sousa

**Comment by psaulus** [comment]
Ok, thank you very much! I will check it.

**[Edited]**
On first view everything looks good. Thanks and I'm closing issue. :)
