### ISSUE TITLE
Validate method

### ISSUE THREAD

**Issue by Shi974** [tiagomichaelsousa/LaravelResources#23]
Hello ! I just downloaded your package and I think it's great ! It really increases productivity, I only wish I discovered it sooner.

There's one thing I'm wondering though, maybe a silly thing. Why not use _validate()_ method in the controller instead of _request -> all()_ ?

Thanks again for that great package.

**Comment by tiagomichaelsousa** [comment]
Hi @Shi974, thank you for your feedback.

You are right, it should use the `validate()` method. ` $request->all()` will be replaced by the `$request->validated()` until the end of the day!

I will update this thread when the changes will be made on **packagist**, after that you just have to update your composer file. 

And thank you, one more time! 🚀

**Comment by Shi974** [comment]
Hey @tiagomichaelsousa , I will be waiting for the next update then. Happy to help 👍

**Comment by tiagomichaelsousa** [comment]
@Shi974 the changes are already update on packagist! 🚀
you can pull now the new version by updating your **composer.json** file with  `"tiagomichaelsousa/laravelresources": "^1.7"`
I also added new migrations, seeds and factories boilerplates, hope you enjoy 🔥

Let me know if its all okay for you 
Thank you,
