### ISSUE TITLE
when i try to install laravelResource on laravel 10

### ISSUE THREAD

**Issue by AliRock86** [tiagomichaelsousa/LaravelResources#80]
/composer.json has been updated
Running composer update tiagomichaelsousa/laravelresources
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tiagomichaelsousa/laravelresources[v1.0, ..., v1.3] require illuminate/support ~5|~6 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - tiagomichaelsousa/laravelresources[v1.4, ..., v1.7] require illuminate/support ^7.0 -> found illuminate/support[v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - tiagomichaelsousa/laravelresources[v1.8, v2.0] require illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - tiagomichaelsousa/laravelresources v2.0.1 requires illuminate/support ^7.0|^8.0|^9.0 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires tiagomichaelsousa/laravelresources * -> satisfiable by tiagomichaelsousa/laravelresources[v1.0, ..., v1.8, v2.0, v2.0.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require tiagomichaelsousa/laravelresources:*" to figure out if any version is installable, or "composer require tiagomichaelsousa/laravelresources:^2.1" if you know which you need.

**Comment by tiagomichaelsousa** [comment]
Hey there 👋

I didn't have time to upgrade this package will all the changes that were made in the stubs for laravel 10.
Also, I think with all the things that were added this package is kinda deprecated after the laravel 9.x.

If you feel that this package may help you somehow for your current development experience please let me know i can try to make the effort to make it compatible with laravel 10.

You are also free to create a PR for it and contribute 🤗

**Comment by tiagomichaelsousa** [comment]
I decided to give it a try really fast to kinda unblock you @AliRock86 😎

You can have a look into the release[here](https://github.com/tiagomichaelsousa/LaravelResources/releases/tag/v3.0.0) 👀

Please let me know if you need anything else and if I can close the issue 🤗

**Comment by AliRock86** [comment]
Thanks 🔥💥
